apiVersion: apps/v1
kind: Deployment
metadata:
  name: items
  labels:
    app: items
spec:
  replicas: 1
  selector:
    matchLabels:
      app: items
  template:
    metadata:
      labels:
        app: items
    spec:
      containers:
        - name: items
          image: samburi/items:1.0.3.5
          imagePullPolicy: Always
          ports:
            - containerPort: 9011
          env:
            # - name: SPRING_PROFILES_ACTIVE
            #   value: kubernetes
            - name: ISSUER_URL
              valueFrom:
                secretKeyRef:
                  name: saburi-secret
                  key: issuer-url
                  optional: false
            - name: GATEWAY_URL
              valueFrom:
                secretKeyRef:
                  name: saburi-secret
                  key: gateway-url
                  optional: false                  
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: saburi-secret
                  key: dbhost
                  optional: false
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: saburi-secret
                  key: username
                  optional: false
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: saburi-secret
                  key: password
                  optional: false
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                    name: saburi-secret
                    key: db-port
                    optional: false
---
apiVersion: v1
kind: Service
metadata:
  name: items
spec:
  ports:
    - targetPort: 9011
      port: 80
  selector:
    app: items

# kubectl apply -f items.yml
# kubectl delete -f items.yml
