apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: keycloak
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.2.0
          env:
            - name: KC_DB
              value: mysql
            - name: KC_DB_URL
              value: jdbc:mysql://mysql:3306/keycloak?useSSL=false&characterEncoding=UTF-8
            - name: KC_DB_USERNAME
              value: keycloak
            - name: KC_DB_PASSWORD
              value: password
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_SPI_THEME_STATIC_MAX_AGE
              value: "-1"
            - name: KC_SPI_THEME_CACHE_THEMES
              value: "false"
            - name: KC_SPI_THEME_CACHE_TEMPLATES
              value: "false"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: keycloak-themes
              mountPath: /opt/keycloak/themes
      volumes:
        - name: keycloak-themes
          configMap:
            name: keycloak-themes
      command: ["start-dev"]
