apiVersion: apps/v1
kind: Deployment
metadata:
  name: easyvalues
  labels:
    app: easyvalues
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easyvalues
  template:
    metadata:
      labels:
        app: easyvalues
    spec:
      containers:
        - name: easyvalues
          image: samburi/easyvalues:1.0.9
          imagePullPolicy: Always
          env:
          - name: VUE_APP_AUTH_URL
            value: "https://auth.capidattex.net/auth"
          - name: VUE_APP_API_URL
            value: https://api.capidattex.net
                 
---
apiVersion: v1
kind: Service
metadata:
  name: easyvalues
spec:
  # type: LoadBalancer
  
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app: easyvalues

# kubectl apply -f k8s/deployment.yaml