apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicegateway
  labels:
    app: servicegateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicegateway
  template:
    metadata:
      labels:
        app: servicegateway
    spec:
      containers:
        - name: servicegateway
          image: samburi/service-gateway:1.0.3.7
          imagePullPolicy: Always
          env:
            - name: ORG_URL
              value: https://organisation.capidattex.net
            - name: ISSUER_URL
              valueFrom:
                secretKeyRef:
                  name: saburi-secret
                  key: issuer-url
                  optional: false
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: saburi-secret
                  key: client-secret
                  optional: false
          ports:
            - name: http
              containerPort: 8089
            - name: https
              containerPort: 8443

---
apiVersion: v1
kind: Service
metadata:
  name: servicegateway
spec:
  # type: LoadBalancer

  ports:
    - name: http
      port: 80
      targetPort: 8089
  selector:
    app: servicegateway
# kind load docker-image samburi/service-gateway:1.0.2.3
# kubectl apply -f deployment.yml
#  kubectl apply -f k8s/deployment.yml
#
# kubectl get pod keycloak-7c56d74d58-4nwml --template='{{(index (index .spec.containers 0).ports 0).containerPort}}{{"\n"}}'
# kubectl port-forward deployment/keycloak 8089:8089
