kind: ConfigMap
apiVersion: v1
metadata:
  name: servicegateway
  labels:
    app: servicegateway
data:
  application.yml: |-
    server:
      port: ${PORT:8089}
    issuer:
      url: ${ISSUER_URL:http://localhost:8080/auth/realms/saburi-realm}

    resilience4j.circuitbreaker:
      configs:
        default:
        
          minimumNumberOfCalls: 5
          permittedNumberOfCallsInHalfOpenState: 3
          automaticTransitionFromOpenToHalfOpenEnabled: true
          waitDurationInOpenState: 2s
          failureRateThreshold: 50
          eventConsumerBufferSize: 10
          recordExceptions:
            - org.springframework.web.client.HttpServerErrorException
            - java.io.IOException
          ignoreExceptions:
            - java.lang.IllegalStateException
        shared:
          slidingWindowSize: 100
          permittedNumberOfCallsInHalfOpenState: 30
          waitDurationInOpenState: 1s
          failureRateThreshold: 50
          eventConsumerBufferSize: 10
          ignoreExceptions:
            - java.lang.IllegalStateException
      instances:
        backendA:
          baseConfig: 
        backendB:
          slidingWindowSize: 10
          minimumNumberOfCalls: 10
          permittedNumberOfCallsInHalfOpenState: 3
          waitDurationInOpenState: 1s
          failureRateThreshold: 50
          eventConsumerBufferSize: 10
    management:
      endpoints:
        web:
          exposure:
            include: "*"
        restart:
          enabled: true
           
    spring:
      main:
        allow-bean-definition-overriding: true
        web-application-type: reactive 
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: ${issuer.url}
          client:
            provider:
              saburi-realm-provider:
                issuer-uri: ${issuer.url}
                user-name-attribute: preferred_username
            registration:
              keycloak-easy-values:
                provider: saburi-realm-provider
                client-id: easy-values
                client-secret: ${CLIENT_SECRET:RF7mod36HNtKPS5Um56Xkctj2IyZtERn}
                authorization-grant-type: authorization_code
                redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
                scope: openid
      cloud:
        kubernetes:
          discovery:
            enabled: true
            all-namespaces: true
        loadbalancer:
          ribbon:
            enabled: false
        gateway:
          default-filters:
             - TokenRelay
          discovery:
            locator:
              enabled: true
              # locowerCaseServiceId: false
          routes:
          -   id: organisation
              uri: https://organisation.capidattex.net
              predicates:
                - Path=/organisation/**, /companies/**, /branches/**, /tenants/**, /idgenerator/**
          -   id: lookup
              uri: https://lookup.capidattex.net
              predicates:
                - Path=/lookupobjects/**,/lookupdata/**,/enums/**,/measuregroups/**, /itemcategories/**, /items/**, /currencies/**
          -   id: profile
              uri:  https://profile.capidattex.net
              predicates:
                - Path= /profile/enums/**, /countries/**, /districts/**, /counties/**, /subcounties/**, /parishes/**, /villages/**, /profiles/** , /profilepictures/**         
         
          -   id: customer
              uri:  https://customer.capidattex.net
              predicates:
                - Path=/customer/enums/**, /accountsgroups/**, /customers/**, /customersponsors/**, /customerledgers/**, /engagements/**
          -   id: accounting
              uri:  https://accounting.capidattex.net
              predicates:
               - Path=/financialperiods/**, /accountcategories/**, /accounts/**, /journals/**, /generalledgers/**, /businesssectionaccounts/**
       
          -   id: sales
              uri:  https://sales.capidattex.net
              predicates:
                - Path=/sales/enums/**, /invoices/**,/invoicedetails/**, /receipts/**, /receiptinvoices/**, /refunds/**
          -   id: banking
              uri:  https://banking.capidattex.net
              predicates:
                - Path=/banking/enums/**,/bankaccounts/**, /bankledgers/**, /banktransfers/**, /banktransactions/**
          -   id: loan
              uri: https://loan.capidattex.net
              predicates:
                - Path=/periods/**, /loanproducts/**, /loan/enums/**, /loanapplications/**, /loanapprovals/**, /loans/**, /loanbills/**,/loanbilldetails/**,/guarantors/**, /loantransitions/**, /loantransactions/**
          -   id: expense
              uri: https://expenses.capidattex.net
              predicates:
                    - Path=/expensegroups/**, /itembudgets/**, /expenses/**, /expensedetails/**
          -   id: shares
              uri: https://shares.capidattex.net
              predicates:
                    - Path=/sharetypes/**,/shares/enums/**, /shareholders/**, /investments/**, /sharetransfers/**, /shareholderledgers/**, /shareholdershares/** 
    security:
      white-listed-paths:
        - /discoveryclientname/
        - /idgenerator/**
        - /actuator/**
        - /logout.html
        - /customer/customername/**
        - /lookupdata/lookupdataname/{id}/{caption}
        - /lookupdata/lookupdataname/**
        - /bankaccounts/bankaccountname/**
        - /currencies/currency/**
        - /customers/customer/**
        - /lookupdata/exists/**
        - /receiptinvoices/mini/**
        - /tenants/mini
        - /tenants/mini/**
        - /branches/branchname/**
        - /branches/devname/**
        - /companies/mini
        - /companies/mini/initialize
        - /companies/mini/devname/**
        - /companies/mini/**
        - /itemcategories/itemcategory/**
        - /businesssectionaccounts/businesssectionitemcategory/**
        - /items/mini/**
        - /bankaccounts/mini/**
        - /financialperiods/mini/active
        - /customers/{referenceType}/{referenceNo}
        - /accountsgroups/businesssectionid/{businessSectionId}
        - /items/mini/{id}
        - /banking/enums/**
        - sales/enums/**
        - /profiles/enums/**
        - /expense/enums/**
        - /shares/enums/**
        - /customer/enums/**
        - /lookup/enums/**
        - /organisation/enums/**

