apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales
  labels:
    app: sales
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sales
  template:
    metadata:
      labels:
        app: sales
    spec:
      containers:
        - name: sales
          image: samburi/sales:1.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9012
          env:
            # - name: SPRING_PROFILES_ACTIVE
            #   value: kubernetes
            - name: ISSUER_URL
              valueFrom:
                secretKeyRef:
                  name: saburi-secret
                  key: issuer-url
                  optional: false
            - name: GATEWAY_URL
              valueFrom:
                secretKeyRef:
                  name: saburi-secret
                  key: gateway-url
                  optional: false                  
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: saburi-secret
                  key: dbhost
                  optional: false
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: saburi-secret
                  key: username
                  optional: false
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: saburi-secret
                  key: password
                  optional: false
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                    name: saburi-secret
                    key: db-port
                    optional: false                  
            - name: KAFKA_URL
              valueFrom:
                secretKeyRef:
                    name: saburi-secret
                    key: kafka-url
                    optional: false 
---
apiVersion: v1
kind: Service
metadata:
  name: sales
spec:
  ports:
    - targetPort: 9012
      port: 80
  selector:
    app: sales

# kubectl apply -f sales.yml
# kubectl delete -f sales.yml
