apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: keycloak
  # type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.5
          args: ["start", "--cache-stack=kubernetes"]
          env:
            - name: KEYCLOAK_ADMIN
              value: "Saburi"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "Bigsize4."
            # - name: KC_HOSTNAME_URL
            #   value: "https://auth.capidattex.net"
            - name: KC_HOSTNAME_STRICT
              value: "false"  # Enable strict hostname resolution
            - name: KC_PROXY
              value: "edge"
            - name: jgroups.dns.query
              value: "keycloak"
            - name: KC_DB
              value: "mysql"
            - name: KC_DB_URL_HOST
              valueFrom:
                secretKeyRef:
                  name: saburi-secret
                  key: dbhost
            - name: KC_DB_URL_PORT
              valueFrom:
                secretKeyRef:
                  name: saburi-secret
                  key: db-port
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: saburi-secret
                  key: username
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: saburi-secret
                  key: password
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
