apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 20Gi  # Specify the size of your volume
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  # Adjust access modes as needed
  persistentVolumeReclaimPolicy: Retain  # Change according to your needs
  storageClassName: standard  # Use an appropriate storage class if you have one
  hostPath:
    path: /mnt/ev-block-volume  # The path where the block volume is mounted on the VM
