apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicegateway
  labels:
    app: servicegateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicegateway
  template:
    metadata:
      labels:
        app: servicegateway
    spec:
      # Add hostAliases to resolve auth.ev.test to 192.168.1.100
      hostAliases:
      - ip: "192.168.1.100"
        hostnames:
        - "auth.ev.test"
        - "org.ev.test"
        - "api.ev.test"
      serviceAccountName: spring-cloud-kubernetes
      containers:
        - name: servicegateway
          image: samburi/service-gateway:1.0.3.7
          imagePullPolicy: Always
          env:
            - name: ORG_URL
              value: http://org.ev.test
            - name: ISSUER_URL
              valueFrom:
                secretKeyRef:
                  name: saburi-secret
                  key: issuer-url
                  optional: false
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: saburi-secret
                  key: client-secret
                  optional: false
            - name: SPRING_CLOUD_BOOTSTRAP_ENABLED 
              value: "true"
            - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLEAPI
              value: "true"                  
          ports:
            - name: http
              containerPort: 8089
            - name: https
              containerPort: 8443

---
apiVersion: v1
kind: Service
metadata:
  name: servicegateway
spec:
  # type: LoadBalancer

  ports:
    - name: http
      port: 8089
      targetPort: 8089
  selector:
    app: servicegateway